version: '3.8'

services:
  mysql:
    image: mysql:8.0.22
    container_name: mysql-digital-bank
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mysql_data:/opt/mysql/data
    env_file:
      - ./config/db.env

  oracle-xe:
    image: gvenzl/oracle-xe:21
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=MyOraclePwd123
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./init:/container-entrypoint-initdb.d
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  oracle_data: {}
  mysql_data: {}
