spring:
  name: digital-bank

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: dev_user
    password: dev_pass
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true

  main:
    banner-mode: off
    output:
      ansi:
        enabled: ALWAYS
    jackson:
      default-property-inclusion: non_null
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher

  logging:
    level:
      root: INFO
      io.github.luaprogrammer.digital_bank: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - [%thread] %-5level %logger{36} - %msg%n"

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: digital-bank-api
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      retries: 2
#      acks: all
#      properties:
#        max.in.flight.requests.per.connection: 1