spring:
  name: digital-bank

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/digital_bank?createDatabaseIfNotExist=true
    username: root
    password: root_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    banner-mode: off
    output:
      ansi:
        enabled: ALWAYS
    jackson:
      default-property-inclusion: non_null
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher